# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3b6906861b909532a1bc21b0f1850c1d399f321f1a7e7e17b272c0783ecaad043bdbd4626091525bd73b24c57145958d8c3997b8508e08818209b246eee4893

test:
  secret_key_base: 1ede2e84603e352cea237331f3e0cbe3be01e2f429632e10729a9abe7f58cd2e287a23f6e52ec909ad66773000ecf0f5a176ce0f663c448f3dc9966f9bbc3347

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
